// Code generated by "stringer -type=Operation -trimprefix=Operation"; DO NOT EDIT.

package diff

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperationDelete - -1]
	_ = x[OperationInsert-1]
	_ = x[OperationEqual-0]
}

const _Operation_name = "DeleteEqualInsert"

var _Operation_index = [...]uint8{0, 6, 11, 17}

func (i Operation) String() string {
	i -= -1
	if i < 0 || i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
