networks:
  shopnexus:
    name: shopnexus
    external: false

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: shopnexus
      POSTGRES_PASSWORD: peakshopnexuspassword
      POSTGRES_DB: shopnexus
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shopnexus
volumes:
  postgres-data:
