networks:
  shopnexus-network:
    name: shopnexus-network
    external: false

services:
  postgres:
    container_name: shopnexus-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: shopnexus
      POSTGRES_PASSWORD: peakshopnexuspassword
      POSTGRES_DB: shopnexus
    volumes:
      - shopnexus-data:/var/lib/postgresql/data
    networks:
      - shopnexus-network
volumes:
  shopnexus-data:
