version: '3.8'

networks:
  shopnexus-network:
    name: shopnexus-network
    external: false

volumes:
  postgres-data:
  redis-data:
  nats-data:


services:
  postgres:
    container_name: shopnexus-postgres
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shopnexus
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-peakshopnexuspassword}
      POSTGRES_DB: shopnexus
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shopnexus-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U shopnexus -d shopnexus" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  redis:
    container_name: shopnexus-redis
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - shopnexus-network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-peaksehopnexuspassword}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  nats:
    container_name: shopnexus-nats
    image: nats:2.11-alpine
    ports:
      - "4222:4222" # Client connections
      - "8222:8222" # HTTP monitoring
    networks:
      - shopnexus-network
    volumes:
      - nats-data:/data
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
